#!/bin/bash
# bash script to generate tiles for house prices for small areas
# to run houseprice.sh


#You need the

#prepare your houseprice.csv
#remove top rows
#rename house price column as houseprice
#remove unnecessary columns, only need LSOAcode, LSOAname and houseprice

#unzip the buildings
echo 'unzipping buildings'
unzip msoabuildingwgs84.zip


#join buildings to house price data
echo 'joining buildings to house price data'
mapshaper-xl msoabuildingwgs84.shp -join data.csv keys=msoa11cd,areacd field-types=areacd:str,areanm:str,areanmhc:str,LAD11CD:str,LAD11NM:str,bhc:num,bhcrank:num,ahc:num,ahcrank:num -o joined.shp


#reduce precisions
mapshaper-xl joined.shp precision=0.0001 -o reducedprecisions.shp

echo 'converting to geojson'
#convert to geojson
#this will take a while (about 15 minutes - and don't expect any sign of life - just see the output filesize creep up)
ogr2ogr -f GeoJSON -t_srs crs:84 -lco COORDINATE_PRECISION=5 incomeest.geojson joined.shp

echo 'generating tiles'
#Make the tiles
#Zoom level 4 to 8
tippecanoe --minimum-zoom=4 --maximum-zoom=9 --output-to-directory z4-8 --full-detail=9 --drop-smallest-as-needed --extend-zooms-if-still-dropping incomeest.geojson
#Zoom level 9
tippecanoe --minimum-zoom=9 --maximum-zoom=9 --output-to-directory z9 --full-detail=11 --no-tile-size-limit incomeest.geojson
#Zoom 10 to 13
tippecanoe --minimum-zoom=10 --maximum-zoom=13 --output-to-directory z10-13 --no-tile-size-limit --extend-zooms-if-still-dropping incomeest.geojson


#move the files together
mkdir tiles
cp -r z4-8/ tiles
cp -r z9/ tiles
cp -r z10-13/ tiles

echo 'downloading MSOA boundaries'
#download generalised msoa geojson
wget https://opendata.arcgis.com/datasets/29fdaa2efced40378ce8173b411aeb0e_2.geojson

echo 'joining income estimates to MSOA boundaries'
#drop fields we don't need
ogr2ogr -f geojson -t_srs crs:84 -sql "SELECT msoa11cd, msoa11nm FROM e29fdaa2efced40378ce8173b411aeb0e_2" bounds.geojson e29fdaa2efced40378ce8173b411aeb0e_2.geojson

#join house prices to boundaries too
mapshaper-xl bounds.geojson -join data.csv keys=msoa11cd,areacd field-types=areacd:str,areanm:str,areanmhc:str,LAD11CD:str,LAD11NM:str,bhc:num,bhcrank:num,ahc:num,ahcrank:num -o boundar.geojson

#drop some more fields
ogr2ogr -f geojson -t_srs crs:84 -sql "SELECT msoa11cd, msoa11nm, areanmhc, LAD11CD, LAD11NM, bhc, bhcrank, ahc, ahcrank FROM boundar" boundaries.geojson boundar.geojson

#tidy up
rm bounds.geojson
rm boundar.geojson

echo 'making LSOA boundaries tiles'
#makes tiles for the lsoa boundaries
tippecanoe --minimum-zoom=10 --maximum-zoom=13 --output-to-directory boundaries --no-tile-size-limit boundaries.geojson

echo 'build for higher zoom levels'
#download generalised msoa geojson
wget https://opendata.arcgis.com/datasets/c661a8377e2647b0bae68c4911df868b_3.geojson

echo 'joining income estimates to MSOA boundaries'
#drop fields we don't need
ogr2ogr -f geojson -t_srs crs:84 -sql "SELECT msoa11cd, msoa11nm FROM c661a8377e2647b0bae68c4911df868b_3" bounds.geojson c661a8377e2647b0bae68c4911df868b_3.geojson

#join house prices to boundaries too
mapshaper-xl bounds.geojson -join data.csv keys=msoa11cd,areacd field-types=areacd:str,areanm:str,areanmhc:str,LAD11CD:str,LAD11NM:str,bhc:num,bhcrank:num,ahc:num,ahcrank:num -o boundar.geojson

#drop some more fields
ogr2ogr -f geojson -t_srs crs:84 -sql "SELECT msoa11cd, msoa11nm, areanmhc, LAD11CD, LAD11NM, bhc, bhcrank, ahc, ahcrank FROM boundar" boundaries.geojson boundar.geojson

#tidy up
rm bounds.geojson
rm boundar.geojson

echo 'making LSOA boundaries tiles'
#makes tiles for the lsoa boundaries
tippecanoe --minimum-zoom=4 --maximum-zoom=9 --output-to-directory boundaries2 --no-tile-size-limit boundaries.geojson


echo 'zipping up files, almost done'
#zip the files up for EC2
zip -r tiles.zip tiles boundaries
echo 'DONE!'
